### ISSUE TITLE
scam pool

### ISSUE THREAD

**Issue by Karasur** [hpool-dev/chia-plotter#23]
Never use this pool, they ask mnemonic pass from your wallet, so one day the just steal you coins. Then will change phone number in your account so you could not do anythining even withdraw yor coins!

**Comment by h9-dev** [comment]
> Never use this pool, they ask mnemonic pass from your wallet, so one day the just steal you coins. Then will change phone number in your account so you could not do anythining even withdraw yor coins!

The signature information will not include your passphrase and the private key data of the payment address related to the passphrase.
If you are not at ease, then please do not use the address generated by this passphrase to receive any XCH.

If you are very worried about security, then please use google authenticator.

**Comment by chris-chia-chia** [comment]
May be it is a scam. Please explain to me why both my PC and server plots have gone offline? I have my PC at home and then a dedicated server that I have rented which is a different location in another country, both connected to the same account. Is this the reason for my offline plots? They worked before... Please advise, lack of English support is frustrating although you have made an English version.

**Comment by chris-chia-chia** [comment]
Seems their network was down, everything is working fine now.
