### ISSUE TITLE
绘图程序运行75%出错！

### ISSUE THREAD

**Issue by cppmis** [hpool-dev/chia-plotter#27]
绘图程序运行到75%时出错，日志文件显示如下：

Progress: 75.000
Time for phase 3 = 15590.450 seconds. CPU (77.480%) Thu Apr 29 08:24:27 2021

Starting phase 4/4: Write Checkpoint tables into "d:\\plot-k32-2021-04-17-28-22-3cf7c3c125c29615f68b5602c8ae8a10ee74c88d50292bdf3a8577debcd29c09.plot.2.tmp" ... Thu Apr 29 08:24:27 2021
        Starting to write C1 and C3 tables
        Bucket 0 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
Progress: 75.000
        Bucket 1 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
        Bucket 2 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
        Bucket 3 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
        Bucket 4 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
        Bucket 5 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
        Bucket 6 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
        Bucket 7 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
Progress: -2935.552
        Bucket 8 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
        Bucket 9 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
        Bucket 10 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
        Bucket 11 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
        Bucket 12 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
        Bucket 13 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
        Bucket 14 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
        Bucket 15 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
Progress: -5946.104
        Bucket 16 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
        Bucket 17 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
        Bucket 18 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
        Bucket 19 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
        Bucket 20 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
        Bucket 21 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
        Bucket 22 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
        Bucket 23 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1
Progress: -8956.657
        Bucket 24 QS. Ram: 4.440GiB, u_sort min: 0.750GiB, qs min: 0.375GiB. force_qs: 1

**Comment by hkfires** [comment]
这不是出错，是正常的
