### ISSUE TITLE
When you update the plotter???

### ISSUE THREAD

**Issue by evgenTraytyak** [hpool-dev/chia-plotter#28]
At the moment the size of the temp plot size exceeds 340gb, when the new official plotter reduced the size to 260gb, which allows you to run 3 plotting processes in parallel using 1tb ssd nvme.
Or explain how to use the official chia plotter that the hpool miner successfully picked up these plots.

**Comment by SametBasturkk** [comment]
why you closed?

**Comment by inSight-mk1** [comment]
Just use official CLI to plot, remember to assign the correct ppk and fpk.
