### ISSUE TITLE
关于在线算力

### ISSUE THREAD

**Issue by madmmmax** [hpool-dev/chia-plotter#29]
请问下为什么在线算力刷新不出来？？
另外我给矿机改了个名字，在线矿机就显示成2个了，这是为什么？
我的理解是，P盘的bat设置了矿池key，但是已经用官方软件P好的文件导入到HPOOL里，是不是没有经过签名所以认不出来，只能用HPOOL P好的文件才有算力？

![Snipaste_2021-04-30_00-55-50](https://user-images.githubusercontent.com/64778400/116589485-46301980-a94f-11eb-9024-6cd24d19f980.png)
![Snipaste_2021-04-30_00-55-58](https://user-images.githubusercontent.com/64778400/116589492-48927380-a94f-11eb-9ce6-9009b5f6e2d4.png)
![Snipaste_2021-04-30_00-56-04](https://user-images.githubusercontent.com/64778400/116589494-48927380-a94f-11eb-93a0-42cdd812c403.png)

**Comment by madmmmax** [comment]
现在在线算力有显示了。
在线矿机也正常了，改名前的已经显示离线了。

**Comment by Hubert51** [comment]
大概过了多久，在线算力能正常显示？
