### ISSUE TITLE
如何证明你们的签名软件不会保存用户的助记词（私钥）

### ISSUE THREAD

**Issue by ansonlianson** [hpool-dev/chia-plotter#6]
太多人说矿池会盗取矿工的私钥了，说签名软件等于把自己的私钥提交给矿池。即使告诉他们签名软件不联网都可以使用，公钥签名不能逆向推私钥，也不相信，并且攻击推荐使用矿池的人。
是否有源代码或者其他方式完全证明你们不会盗取私钥

**Comment by keliew** [comment]
https://hpool.com/help/tutorial/Chia%E6%8C%96%E7%9F%BF%E6%95%99%E7%A8%8B
教程写得明明白白  必须提交助记词

**Comment by hpool-dev** [comment]
> 太多人说矿池会盗取矿工的私钥了，说签名软件等于把自己的私钥提交给矿池。即使告诉他们签名软件不联网都可以使用，公钥签名不能逆向推私钥，也不相信，并且攻击推荐使用矿池的人。
> 是否有源代码或者其他方式完全证明你们不会盗取私钥

矿池没有也不会获取你的『助记词』，也不会保存此助记词对应的你们钱包地址的私钥。如果不放心，请不要用这个『助记词』生成的地址保存任何 XCH。
目前还没有开源的计划。

**Comment by hpool-dev** [comment]
> https://hpool.com/help/tutorial/Chia%E6%8C%96%E7%9F%BF%E6%95%99%E7%A8%8B
> 教程写得明明白白 必须提交助记词

签名输入的助记词只是为了生成在矿池挖矿的信息，其中绝不包含你的『助记词』以及这个助记词对应的钱包地址的私钥。如果不放心，请不要用这个『助记词』生成的地址保存任何 XCH。

**Comment by hpool-dev** [comment]
为了保持竞争力，目前不会开源签名软件的代码。以后会开源。
