### ISSUE TITLE
1.0.5版本扫出的plot比1.0.4.1版本的要少

### ISSUE THREAD

**Issue by hkfires** [hpool-dev/chia-plotter#7]
使用你们的p图工具p出来的plot，一共有9个，使用1.0.4.1版本的hpool-miner-chia-gui，可以识别全部9个，而使用刚更新的1.0.5版本，只能识别8个，反复替换试过，确实是新版本带来的问题，希望能够修复。
如图所示：
![1 0 4 1](https://user-images.githubusercontent.com/10558748/115400463-e6819200-a21b-11eb-91bd-5dda7c187834.jpg)
![1 0 5](https://user-images.githubusercontent.com/10558748/115400482-eb464600-a21b-11eb-8c65-f11f32d1ef9c.jpg)

**Comment by hpool-dev** [comment]
> 使用你们的p图工具p出来的plot，一共有9个，使用1.0.4.1版本的hpool-miner-chia-gui，可以识别全部9个，而使用刚更新的1.0.5版本，只能识别8个，反复替换试过，确实是新版本带来的问题，希望能够修复。
> 如图所示：
> ![1 0 4 1](https://user-images.githubusercontent.com/10558748/115400463-e6819200-a21b-11eb-91bd-5dda7c187834.jpg)
> ![1 0 5](https://user-images.githubusercontent.com/10558748/115400482-eb464600-a21b-11eb-8c65-f11f32d1ef9c.jpg)

请移步到 https://github.com/hpool-dev/chia-miner/issues/18 .
