### ISSUE TITLE
使用hpool的plots和官方plots区别？

### ISSUE THREAD

**Issue by iRickcoder** [hpool-dev/chia-plotter#9]
在密钥绑定后，
我使用官方程序生成的plot文件可以用于hpool的矿池挖矿，使用这个hpool生成的plot文件也可以，那是否意味着两个plots程序生成的文件是具有相同**使用特性**？即：
1. 生成的plot文件可以用于官方钱包挖矿也可以用于矿池挖矿
2. 生成的plot文件与钱包绑定，不可他人使用

另外，可以简单解释一下**hpool plots**使用的frk和ppk填写的作用吗？是不是这两个公钥代表了我的钱包唯一地址还是？

**Comment by iRickcoder** [comment]
去看了一下官方源码，所以这个frk和ppk也是官方使用的对么？
就是说1,2点完全正确？

**Comment by hpool-dev** [comment]
是的，文件是完全一致的，都可以用于在矿池和 Solo。
早期 chia 钱包 P必须开启钱包，意味这你的私钥会被其他任何可以接触到这台电脑的人获取，我们的plotter 只需要公钥。目前 chia 钱包也支持了使用公钥，来避免可能的私钥泄露。
